

##############################################
#Model
MODEL:
    BACKBONE_NAME: "resnet18"
    WEIGHTS: ""
    USE_IMAGENET_BACKBONE: True


############################################
#Dataset
DATA:
    DATA_SRC: "" # data src path
    TRAIN_LIST: "K:\\_GDISK\\dty\\robbin_topborder_det_stage\\DEL\\all_train.txt"
    TEST_LIST: "K:\\_GDISK\\dty\\robbin_topborder_det_stage\\DEL\\all_test.txt"
    NAME: "robbing_break_topborder_baseline"
    CLASSES_BALANCED: False
    MEAN: (0.485, 0.456, 0.406)
    STD: (0.229, 0.224, 0.225)
    AUGMENT:
        ROTATION: 10.0
        GAMMA: 0.1
        HFLIP: true
        VFLIP: true
        SHUFFLE_COLOR: true
        RESIZE: [256,256] # width height
        CROP: [224,224] # width height

SOLVER:
    LR_BASE: 0.001
    LR_POLICY: "cosine"
    GRADIENT_MAX: -1
    EPOCHS: 50
    BATCH_SIZE: 32
    OUTPUT_FOLDER: "OUTPUT\\robbing_break_topborder_resnet18"
