

##############################################
#Model
MODEL:
    BACKBONE_NAME: "resnet18"
    WEIGHTS: ""
    USE_IMAGENET_BACKBONE: True


############################################
#Dataset
DATA:
    TRAIN_LIST: "J:\\stain_bottom\\stain_train.txt"
    TEST_LIST: "J:\\stain_bottom\\stain_test.txt"
    NAME: "stain_bottom"
    CLASSES_BALANCED: False
    MEAN: (0.485, 0.456, 0.406)
    STD: (0.229, 0.224, 0.225)
    AUGMENT:
        SHEAR: (0.05,0.05) #H,W
        BLUR: 3 #kernel size
        GAMMA: 0.4
        HFLIP: true
        VFLIP: false
        COLOR: false
        RESIZE: [96,96] # Width,height

SOLVER:
    LR_BASE: 0.001
    LR_POLICY: "cosine"
    GRADIENT_MAX: -1
    EPOCHS: 50
    BATCH_SIZE: 32
    OUTPUT_FOLDER: "OUTPUT"
