

##############################################
#Model
MODEL:
    BACKBONE_NAME: "resnet50"
    WEIGHTS: ""
    USE_IMAGENET_BACKBONE: True


############################################
#Dataset
DATA:
    TRAIN_LIST: "G:\\noise_vs_stainlike\\stain_train.txt"
    TEST_LIST: "G:\\noise_vs_stainlike\\stain_test.txt"
    NAME: "classical_classifier"
    CLASSES_BALANCED: False
    MEAN: (0, 0.0, 0.0)
    STD: (255.0, 255.0, 255.0)
    AUGMENT:
        ROTATION: 10.0
        GAMMA: 0.1
        HFLIP: true
        VFLIP: false
        SHUFFLE_COLOR: true
        RESIZE: [112,112] # width height
        CROP: [96,96] # width height

SOLVER:
    LR_BASE: 0.001
    LR_POLICY: "cosine"
    GRADIENT_MAX: -1
    EPOCHS: 50
    BATCH_SIZE: 32
    OUTPUT_FOLDER: "train_out/stain_bottom_resnet50"

ONNX:
    INPUT_SHAPE : [1, 3, 96, 96]
    NUM_CLASSES : 2
    CLASSES: ["noise","stainlike"]
