MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "pretrained/imagenet_lite_iter_2000000.pkl"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "PVA-FPN-RETINANET"
    FREEZE_CONV_BODY_AT: 1
  RESNETS:
    RES2_OUT_CHANNELS: 48 # first of four outputs
    BACKBONE_OUT_CHANNELS: 256 #last of four outputs
    BACKBONE_OUT_CHANNELS_SHRINK: 4
  FCOS:
    NUM_CLASSES: 2 # include background
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
    NUM_CLASSES: 2
  ROI_BOX_HEAD:
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("voc_2007_trainval","voc_2012_trainval")
  TEST: ("voc_2007_test",)
INPUT:
  MIN_SIZE_TRAIN: (512,768,896)
  MAX_SIZE_TRAIN: 896
  MIN_SIZE_TEST: 512
  MAX_SIZE_TEST: 896
  #PIXEL_MEAN: [0.408, 0.447, 0.470]
  #PIXEL_STD: [0.289, 0.274, 0.278]
  #TO_BGR255: False  
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 2
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  #STEPS: (30000, 50000, 60000)
  MAX_ITER: 65000
  IMS_PER_BATCH: 16
  WARMUP_ITERS: 500
  WARMUP_METHOD: "constant"
  SECHEDULE: "cosine"  
TEST:
  DETECTIONS_PER_IMG: 100
  BBOX_AUG:
    ENABLED: False
    H_FLIP: True
    SCALES: (400, 500, 600, 700, 896)
    MAX_SIZE: 896
    SCALE_H_FLIP: True
OUTPUT_DIR: "train_out_stain_bottom"
